version: '3'

services:
  mongo:
    image: mongo:6.0.4
    container_name: mongo
    ports:
      - 27017:27017

#  mongo:
#     image: bitnami/mongodb:4.4.14-debian-10-r33
#     ports:
#       - 27017:27017
#     environment:
#       - MONGODB_ROOT_PASSWORD=root 