version: '3'

services:
  # mongo:
  #   image: mongo:6.0.4
  #   container_name: mongo
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=catalog
  #     - MONGO_INITDB_ROOT_PASSWORD=catalog
  #     - MONGO_INITDB_DATABASE=catalog

 mongo:
  image: bitnami/mongodb:4.4.14-debian-10-r33
  container_name: mongo-catalog
  volumes:
    - mongo_data:/bitnami/mongodb
  expose:
    - 27017
  environment:
    - MONGODB_ROOT_PASSWORD=catalog 
  networks:
    - internal

 catalog:
  image: maven:3.9-amazoncorretto-19
  container_name: catalog
  expose:
    - 8081
  volumes:
    - .:/app
    - maven-repo:/root/.m2
  working_dir: /app
  command: mvn spring-boot:run
  environment:
    - EUREKA_HOST=discovery-server
  networks:
    - spring_microservices
    - internal

volumes:
  maven-repo:
  mongo_data:

networks:
  internal:
  spring_microservices:
    external: true